### ISSUE TITLE
Create a --transitive-last option

### ISSUE THREAD

**Issue by JakeSiFive** [sifive/wake#1110]
Right now the wake database tracks its runs and can give you all the jobs that were run in the last run. However if a job was run more than one wake run ago that job's wake run will *stay* tagged as being from that run despite being used in the latest run. This means that --last only shows the jobs that were actually executed rather than all the jobs that the user truly used which is probably more what the user *actually* wants most of the time.

To do this we need to get all the jobs that were used *transitively* by anything that ran in the latest run...additionally if nothing is run because everything was cached we need someway of handling that. This is quite tricky because of the following situation

```
$ wake myFirstThing
    ...
$ wake mySecondThing
   ...
$ wake myFirstThing
   ...
$ wake --transitive-last
```

If all we did was look at the jobs from the latest wake run and then transitively backtrack their deps in the database we wouldn't actully find any jobs because there would be not roots...worse we can't just look back until we find a run that actully had some jobs assciated with it because that might be a totally different job (see mySecondThing). This seems to imply that we need some other kind of tracking for the jobs that were used in this run of wake. We should probably have a new table that tracks this information I think.

**Comment by azidar** [comment]
It seems to me that this "transitive" option could be appended to most database queries, e.g. with `--failed` as well as `--last`. Honestly, I think this would be an incredibly useful flag that I'd use a lot.

**Comment by JakeSiFive** [comment]
Maybe a better way to do this would be to make transitive the default behavior and then add a flag like "--only-if-executed" to do the current behavoir

**Comment by azidar** [comment]
You are suggesting making this is the default for only the database queries, right? But for running a job (with say the `-v` flag on), it will only print what is executing, right? Would it make sense to add this flag as well for running a wake job, so it displays the transitive output as well?

**Comment by mwachs5** [comment]
> Would it make sense to add this flag as well for running a wake job, so it displays the transitive output as well?

Personally, this change is a nice-to-have but less important than the database version.

One thing to consider is that the database seems to not currentl record the log that it was destined for, so the "what color would this have been if displayed interactively" is not stored in the database?

**Comment by jackkoenig** [comment]
I would vote against changing the default behavior of `-v` to be `--transitive` (but like the idea of being able to selectively apply `--transitive`). The reason being that it would suggest to users that it is, in fact, running all of the jobs each time even when that is not the case. 

Anyway, I agree that transitive behavior for `-v` is less important than the database query versions. I *do* agree that database queries should be transitive by default because, unlike the case of `-v`, you are explicitly querying things you know that have run and the distinction of which previous run the job occurred during is far less relevant.

**Comment by JakeSiFive** [comment]
Yee, Jack's conclusions match my own. That makes me feel more confident.

For what its worth, internally we talked about having non-executed jobs always re-emit and we decided against it because you can always do the per-job work around. Of the ways we imagined it working, we decided that the current way was the best. That isn't fully decided but I think that's the way the Wake team is likely to land on that particular issue pending any new evidence. Specifically I think that the current behavior gives everyone what they need. The people that want things to always print can do that and the people that don't want things to always print can do that too. Between the two ways you can do this job by job (default always print, default only print on execute) defaulting to always print would probably not get un-done as much as we would like because no one would bother adding it and it would become a constant issue in code review. On the other hand the cases we're aware of where we really want to see all the output are handled by just a handful of cases of applying the "always print" work around.

**Comment by azidar** [comment]
To summarize what I think we are concluding:

 1. `wake -v --transitive myJob` should reemit all output of all steps, regardless of what was actually executed
 2. `wake -v myJob` will only emit output for what was actually executed
 3. `wake -v --last` will emit the transitive outputs
 4. `wake -v --last --only-if-executed` will emit the outputs for what was actually executed

Did I get that right?

**Comment by azidar** [comment]
It's a bit weird to me that `-v` defaults to different things whether its a job run or database query.. Maybe can get do a `-v` and `-V` flag, where `-v` is emit output non-transitively, and `-V` is emit output transitively ?

**Comment by ag-eitilt** [comment]
That's my understanding, except that I'd leave off the `-v` flags, especially for 3 and 4.  There's a bit more cause for them in 1 and 2, but I really don't want the unthinking invocation to be "add `-v`" -- if some job emits output you should be seeing every time, it should be updated with `setPlanStdout logReport` (or `job.getJobStdout | println`), and otherwise people should only be using `-v` if they're debugging something.

**Comment by JakeSiFive** [comment]
Well 1. isn't decided and we probably wouldn't call it `transitive` but we might add an environment variable for it. I think the wake team is leaning towards modification of the job code itself to ensure that things you want to be always printed are always printed. That way its on a per job basis and we're not using overly aggressive means to getting there. An environment variable isn't out of the question though.

As for the `-v` confusion, its better to think of database options as being for an entirely different command and they both happen to have `-v`. Also with the changes @V-FEXrt just landed you probably won't need `-v` anymore because the default will be more helpful. The hope is that people just stop using `-v` entirely and that we give them better tools and show them how to use wake more skillfully than using hammers like that.

**Comment by azidar** [comment]
> if some job emits output you should be seeing every time

To try and clarify the conversation, what I see from the output of a wake command is dependent on:

1. The flags I gave wake
2. The state of the database
3. The job library code

What I want as a user is a set of flags which I can guarantee will give me the same output on my screen, completely independent of the state of the database and the job library code. Obviously, job library code should decide what is put on my screen, but the *stability* of what is output should not be dependent on the job library code.

I think that is perhaps where I get concerned is the reasoning that if I want stability on my job outputs, I should update the job code. What I think is more desirable is to never emit something which isn't stable, because it can give users the illusion that the output they are seeing is stable, which is isn't.

The question of what is default/not-default is personally a secondary concern to me, which I am fine deferring on. What I actually care about is this stability guarantee.

**Comment by V-FEXrt** [comment]
I've highlighted below in meetings and one off conversations but I'd like to put them here as well for completeness. Will be a spattering of thoughts that aren't necessarily related. 

1. It's not possible to ever have a guarantee on consistent screen output; even if we completely disregard caching. Jobs run in a random order and thus will output their stdout/stderr in a a random order as well. That can't be resolved without giving up parallelism.
2. The output of wake should never be assumed to be consistent in a "machine readable" way. Wake should be the top level invocation from a human (or a CI bot only checking success/fail) and its stdout/stderr shouldn't be parsed 
3. Adding _more_ output from wake seems like the wrong direction. There are targets we build internally that already emit so many scala warnings that the output is all but useless for a human to scan/read. Always printing stdout/stderr will exacerbate this issue and make wake's output in large projects even more meaningless 
4. Taking away output is actually something I'm generally for. I'd like wake to only output execution summaries and leave the stdout/stderr reporting to some other invocation like `--last`. (I'm imaging something like `Analyzed 5000 jobs. 3500 replayed from database, 1000 replayed from shared cache, 499 executed, 1 failed`). However; this doesn't work since there are users who run very long jobs and need to be able to CTRL+C if they see the job they care about start to fail.
5. #3 and #4 imply to me that _what_ should be output _when_ is *heavily* dependent on the job itself thus only the given job knows the correct answer
6. Any default is going to be wrong for someone. It'll either print too much, print too little, or print the right amount of the wrong thing
7. The ENV var/CONFIG file idea feels like a really fair middle ground. If someone wants to request/overwrite their own default it gives them that power. Seems like its most equitable to let everyone choose the best default for them vs having a specific flow dictate the default for all wake users  
8: "Defaults" can also be changed with the ./runWake type scripts. If anyone feels particularly strongly then they could make their own `./runWakePrintEverything` or `./runWakePrintNothing` scripts 

All in all; I want to say that I appreciate folks here advocating for wake users. Its is really important to us to know the problems our users are facing and how to improve them. Wake has many different users with many different goals/use cases and we just need to be careful and cautious that we don't make things harder for one user by optimizing for another.

**Comment by azidar** [comment]
Thanks for the summary @V-FEXrt !

I think having the ability to do `runWakePrintEverythingIncludingFromCachedJobs`, `runWakePrintOnlyFromExecutingJobs`, and `runWakePrintNothingExceptWakeStatusStuff`, and `runWakePrintNothing` are all use-cases that have their place and I'd love them to be described/documented in a way that is easily discoverable by a user.

**Comment by V-FEXrt** [comment]
Okay after a quick chat with @JakeSiFive I think we are talking about 2 (well 3 if you count the adjacent discussion over logging) things here. I want to split this up to keep conversation/progess focused and targeted.

The 3 things are:

1) There is a bug where `--last` doesn't return a useful output for most users since it only captures jobs that were just executed and ignores cached jobs
2) There is a feature request to optionally capture all dependencies of jobs captured by the "base command"
3) There is the larger discussion about what wake the tool emits to stdout/stderr on successive runs.

Lets table 3 for now. We are working on a larger doc/discussion for that and its not immediately relevant here 

For 1. This is a _bug_ that needs to be fixed for wake to do the correct thing. Fixing the bug is a high priority task. The current proposal is to add `--last-used` and `--last-executed` flags with `--last` mapping to `--last-used`

For 2. This is a feature request to optionally capture more output with the various database inspection commands. We should file this as a separate feature request and track it appropriately. I can see this being a useful tool to have but its less of an immediate need compared to 1.

I should have a PR up for 1 relatively soon then I need to make a quick diversion to some shared caching tasks. After that we can review how 1 went and evaluate the priority on 2

**Comment by JakeSiFive** [comment]
Ashley has updated this as he said he would with --last-used and --last becoming the same as --last-used. I'll open another lower priority ticket for --transitive as a separate flag.
