### ISSUE TITLE
Wake doesn't warn for impossible `data` case constructor patterns in `match`

### ISSUE THREAD

**Issue by bmitc** [sifive/wake#1230]
Edit: Have adjusted the title based upon this effectively being a feature request. See discussion/comments below.

----

During a PR review, I noticed code very similar to the below, where someone was matching against `(Some <option value>)`. However, the code was not generating a warning or error.

```wake
export def test =
    match (Some None)
        Some x = x
        None = None
```
Wake should be warning or erroring here that the second pattern clause can never match. At present, I'm not sure if this error is due to the `Option` or the constructor application.

For example, in code like the below, Wake does properly warn.
```wake
export def test =
    match 2
        _ = 2
        2 = 2
```
The error reported is `pattern is impossible to match`. I should note though that the VS Code extension highlights the 2 to the *right* of the `=`. I think this should be adjusted to highlight the pattern, in this case the 2 to the *left* of the `=`, since the pattern is what is incorrect, not the return expression.

**Comment by ag-eitilt** [comment]
This is a difference between type knowledge and data knowledge.  In your second example, Wake's able to realize that the `_` will match every possible Integer, and thus that your `2` case is a duplicate which won't be reached.  In your first, it never actually looks at what the value of the Option might be, just at its type and it "knows" that every Option has two potential constructors.  This would likely require a fair bit of static analysis in the parser and delaying/rewriting that warning to occur within that analysis phase rather than the simpler typechecker; I think I remember some relatively-recent GHC release proudly talking about getting this same thing working in *some* cases, but I can't find that post with a (very) brief scan.

Of course, I don't know the parser internals so I'm basically just making that entire thing up, but it seems like a reasonable explanation.
