### ISSUE TITLE
`wake-format` removes relative indentation in some cases of multiline strings

### ISSUE THREAD

**Issue by bmitc** [sifive/wake#1288]
In some cases, `wake-format` will remove relative indentation between lines inside a multiline string `"""`. Note: I have not tested the below with Wake's other multiline string syntax of `"%...%"` since it's my understanding that that will eventually be obsoleted in favor of `"""`.

This is best seen via some reproducible examples. Each example code block should be viewed as an entire `.wake` file. This does matter in terms of the issue surfacing or not.

This code:

```wake
    def cmd1 =
        """
        if [ -f %{path} ]; then
            echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
        fi
        """

def cmd2 =
    """
    if [ -f %{path} ]; then
        echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
    fi
    """

def test =
    def cmd =
        """
        if [ -f %{path} ]; then
            echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
        fi
        """

    cmd

export def writeIfChanged =
    require Pass filehash =
        def cmd =
            """
            if [ -f %{path} ]; then
                echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
            fi
            """
        Pass cmd

    Pass filehash

```

will be formatted as:

```wake
def cmd1 =
    """
        if [ -f %{path} ]; then
        echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
        fi
    """

def cmd2 =
    """
        if [ -f %{path} ]; then
        echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
        fi
    """

def test =
    def cmd =
        """
            if [ -f %{path} ]; then
            echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
            fi
        """

    cmd

export def writeIfChanged =
    require Pass filehash =
        def cmd =
            """
                if [ -f %{path} ]; then
                echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
                fi
            """

        Pass cmd

    Pass filehash

```

Note that the relative indentation levels between the lines starting with `if`, `echo`, and `fi` have been lost. The expected formatting should have an additional indentation level on the `echo` line. An additional comment regarding formatting style only (not a formatting issue/bug) and as mentioned elsewhere (just mentioning for completeness), is that it would be nice if the formatter didn't change any of these multiline string indentations (aside from the entire `cmd1` block) and left the indentation anchored to `"""`.

While trying to recreate a minimally reproducing example, I noticed that the following code:

```wake
def cmd =
    """
    if [ -f %{path} ]; then
        echo -n $(b2sum -z -l 256 %{path} | awk '{ print $1 }')
    fi
    """

```

is unchanged by `wake-format`, so the formatting occurs correctly here. I haven't been able to whittle it down further yet in terms of what is the trigger for making this issue occur, but hopefully these examples provide a good starting point.

**Comment by richardxia** [comment]
I just wanted to add that I also hit this, except that it also happens even if I indent the string contents from the `"""` quotes. Here's my minimal reproduction:

### Input

```wake
def _ =
    """
        %{x}
            x
    """
```

### Output

```wake
def _ =
    """
        %{x}
        x
    """
```

---

Here's a slightly more complicated example:

### Input

```wake
def _ =
    """
        if %{x}; then
            %{x}
        fi
    """
```

### Output

```wake
def _ =
    """
        if %{x}; then
        %{x}
        fi
    """
```

---

I think the string interpolation has something to do with it, since in the latter example, if you change the body of the `if` from `%{x}` to `x`, it doesn't get unindented.

I'm currently using wake 37.1.1.

**Comment by richardxia** [comment]
Right, I understand that the leading indentation is ignored, but I wasn't sure if the bug in the formatter was related to the indentation, since the formatter is clearly changing the actual string value in the examples we've provided by removing the relative indentation between the `if` block and its body.

**Comment by V-FEXrt** [comment]
Okay, finally got around to working more on this. The issue is 100% interpolation. Basically each half of the interpolation was being considered as its own multiline string when it needed larger context to figure out the real indentation.

I have a branch up that fixes it but I'm waiting on some other PRs to go in before I can create a PR for it

**Comment by richardxia** [comment]
That's great news! Looking forward to having the formatter correctly support this case!
