### ISSUE TITLE
`markFileCleanable` panics when given a socket file

### ISSUE THREAD

**Issue by albertchen-sifive** [sifive/wake#1382]
wake throws this error when trying to run `markFileCleanable socket`
```
shim hash open(socket): No such device or address
wake-hash open(socket): No such device or address
REACHED UNREACHABLE CODE: wake-hash returned Nil lines but we expected 1 lines
```

**Comment by JakeSiFive** [comment]
Proposed solution:

Right now we open and then stat, we should stat and then open instead and proceed as expected on non-sockets. For sockets or any other exotic files (e.g. not a symlink, directory, or regular file) we should return a hash of 1 (similar to how we return a hash of zero for directories) so that this sort of error never occurs.

**Comment by JakeSiFive** [comment]
Ok I think the latest wake-hash change fixes this
