### ISSUE TITLE
'def write' semantics

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#1414]
The `write` call is able to clear out a directory if you're trying to write a file to a particular path.
This can cause unexpected behavior if someone were to  `write "." "foo"`

We could try to limit this to error-out if:
* write outside the workspace would cause a directory delete at all (single file replacement allowed)
* write within the workspace would replace/delete source files
* write within workspace would delete Path(s) created by the current invocation of wake

**Comment by V-FEXrt** [comment]
Yeah those all seem like good error cases, would also be an interesting angle to have a "safe write" that leverages the type system to ensure that something like this cant happen. It would be more restricted than the current `write` but if we can make it good enough for >90% of the use cases then the type checker could product us here and when someone needs an "unsafe write" its an alarm for us to squint at it a lot closer

**Comment by ag-eitilt** [comment]
I think case 3 would be a bare minimum, and should unquestionably cause an error.  Case 2 seems quite reasonable, but does mean that you can't write wake invocations to update (in-place) checked-in artifacts, where the intent is to then immediately `git commit -a` -- I don't think that's a huge loss since an intermediate `cp` works ~~better~~, but I know some dev flows include it.  Case 1 has the potential for being annoying in certain cases, but I feel like those cases are rare enough and the explanation of "trying to overwrite a directory with a file" is clear enough that it's not going to cause too much issue.  My vote's for preventing all three, but I can see an argument for only 1 and 3.

As far as the type of error goes, the first two seem reasonable enough for a simple `Fail`, but I think the third has to be a panic-and-abort: if it's also left as just a `Fail`, then if we create the `Path` object before the write deletes it, we get a `Fail` and continue on if allowed; if we write before the `Path` would be created, then no matter what we're getting a "File output by multiple jobs" total abort.  (2 doesn't suffer the same issue, since either order would abort if we also try to `source` the file.)

**Comment by JakeSiFive** [comment]
> write within workspace would delete Path(s) created by the current invocation of wake

This is a bit tricky to get right but I haven't fully worked out all the issues. I need to go look into this

> write outside the workspace would cause a directory delete at all (single file replacement allowed)

I wonder if we can just say "if it would delete a directory at all", this means that one build can't clobber a previous build with incompatible directory structure which is a bit annoying but we can add a message that just says "if this was intentional, please manually delete this directory and re-run". This should be rare enough that I think we should consider this compromise.

> write within the workspace would replace/delete source files

This should be trivial to implement and is a good thing to add

**Comment by JakeSiFive** [comment]
Do we even need to allow writes outside the workspace?

**Comment by mmjconolly** [comment]
We do have some small number of existing uses of it writing outside of the workspace, but they could also be converted to use `runJob`

**Comment by JakeSiFive** [comment]
That might be worth doing. I'll take an action item to see if I can make `write` not overwrite previously hashed paths for now and I'll go ahead and add the source file check since that should be trival to add.

**Comment by JakeSiFive** [comment]
ok I've got the others worked out in a prototype (with added constraints) but the "does not overwrite files already created by the current invocation" is a bit hard but I've made it so that write can't even delete a directory since I don't *think* we need that (I'll do a few larger builds in succession to see how that works).

**Comment by V-FEXrt** [comment]
This has been completed, going to close the issue
