### ISSUE TITLE
How wake disowns a GUI process.

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#1450]
Wake is good at building a task system. Sometimes it is helpful to start GUI task from wake to use the environment configurations. But wake will not exit until the GUI task closes.

One thing I thought is for wake to disown the GUI process so wake might not wait the process to end. But I dont know how to. And there might be other solutions.

**Comment by JakeSiFive** [comment]
You have a few options:

1) You write a tool that double-forks with a setsid in the middle so that the job is re-parented from wake. You'll need to run without PID namespacing if you use wakebox, or you can run things using a local runner. From wake's perspective the job will terminate immediately but the gui itself should keep running.
2) You can run wakebox outside of wake itself using the spec/result files but you'll still have to run wake to produce those if you don't want to make them by hand.
3) Make your own runner that handles 1 or 2 for you
4) Consider restructuring how you're invoking your tool such that the internal environment is close enough to your external environment that those sorts of things do not matter
5) Just don't use wake for GUIs because its not really designed for that 🤷

**Comment by davidmlw** [comment]
I tried a workaround but failed. 
1. Start a tmux with session name 'sname'
2. Wake invoke `tmux new-window -t sname "GUI"`

If invoked from a shell, `tmux new-window -t sname "GUI"` exit immidiately and the tmux open a new window and hold the new process. We can try GUI with any interactive shell.

But when invoked from wake, the tmux just splash a new windown and then exit. It seems wake owns the new GUI/shell not the tmux process. But I cannot understand how wake killed the process. It was in another shell with tmux.
