### ISSUE TITLE
Question on require statement

### ISSUE THREAD

**Issue by jinrudals** [sifive/wake#1497]
Hi team,

From https://github.com/sifive/wake/issues/1461,

You have mentioned to use `require` statment to get the Path value from `source "path/to/file"`.

But the problem is as follow.

```
from wake import _
from plan_scorer import _

export def compile filename =
    require Pass path =
        source filename
    def job =
        makeExecPlan ("gcc", filename, Nil) (path, Nil)
        | runJob

    job.getJobOutputs

export def run filename =
    require Pass visibles = (compile filename)
    makeExecPlan ("./a.out", Nil) (visibles)
    | runJob
```

I wanted to run the compiled ouput, but after launching
```
wake -vx 'run "test.c"'
```

I get following result.
```
test.wake:14:[30-45]: type error; case 'Fail' returns expression 'compile filename' of type:
    Result a b
  which does not match case 'Pass' which returned type:
    Job
>>> Aborting without execution <<<
```

Since the output type of `getJobOutputs` is `Result (List Path) Error`, I was assuming `require Pass visibles = (compile filename)` should make `visibles : List Path`

So, what's the very easiest way to run some cases?

**Comment by ag-eitilt** [comment]
Sorry, I didn't see this come in.  This is a known and *really annoying* problem in the typechecker (known internally as "reverse type checking"), but fixing it would require a deep rewrite which we don't have the time for at the moment.  Your code is completely correct everywhere you'd *think* to look when being given that error, the actual problem is that `runJob` only has the type `Plan => Job` and the `result Pass visibles` line means that you need to return a `Result` of some kind to match the type inherited from `compile`.  The solution is usually to simply wrap the final value in `Pass`:

```diff
 export def run filename =
     require Pass visibles = (compile filename)
     makeExecPlan ("./a.out", Nil) (visibles)
     | runJob
+    | Pass
```

Your particular case is slightly different since your final value is a `Job` (which has its own concept of failure separate from `Result a Error` wrappers).  If you just want a quick-and-dirty solution to checking if `./a.out` ran successfully, you can replace the `Pass` in the above diff with `getJobStdout`/`getJobStderr`/`getJobOutputs` (you don't care about anything it returned per se, but those functions do perform a return-code check which you *do* care about), but it's not all that much more work to be explicit about what you're doing:

```diff
 export def run filename =
     require Pass visibles = (compile filename)
-     makeExecPlan ("./a.out", Nil) (visibles)
-     | runJob
+    def isOk =
+        makeExecPlan ("./a.out", Nil) (visibles)
+        | runJob
+        | isJobOk
+    if isOk then
+        Pass Unit
+    else
+        failWithError "test execution failed; run `wake --last --failed` for more info"
```

(Note that both `isJobOk` and the "quick-and-dirty" functions only work if `test.c` uses the standard 0-on-success, anything-else-is-failure return values; if it's something like `diff` where you might *want* a non-zero value, you'll need to write a bit more custom framework around the `Job`.)
