### ISSUE TITLE
Natively support file systems with built-in checksumming

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#264]
This is a bit of a pie in the sky feature request, but I've noticed that Wake spends a significant amount of time checksumming files in order to determine whether an input has changed and therefore a build step needs to be rerun. This is particularly onerous when there are many files or when there are large files that take some time to compute the checksum for.

There are some file systems (e.g. ZFS, BTRFS) which encode checksum information in the file system itself. I think that it should be possible to expose this information to Wake so that Wake would only need to compare the file system's checksum against Wake's internal database of checksums, obviating the need to recompute the checksums upon each invocation of Wake.

I think it's worth investigating this, since the runtime savings could be significant.

**Comment by terpstra** [comment]
When it looks like wake is spending time hashing files, ... it's not. Wake is busy because the code in wake itself is slow and wake is just blaming these poor hash Jobs. Hashing is actually extremely fast.

Also, if I did use the filesystem hashes, I would not be able to do shared caching between systems in the future.

**Comment by richardxia** [comment]
Do we have any plans to make the standard output a bit clearer about the fact that it's not actually hashing files?

**Comment by terpstra** [comment]
It's on my TODO list for 0.17, along with actually making wake performance not terrible.
