### ISSUE TITLE
Error: Primitive reference catch is unbound

### ISSUE THREAD

**Issue by saurabhsingh-pvips** [sifive/wake#338]
I've trying to run wake commands on block-pio example of SiFive. I encountered the issue of `Variable reference is unbound` and was suggested to downgrade wake `v0.18.x` to wake `v0.15.x` to fix the issue.

I am unable to run any wake script after the downgrade. Executing any wake script or even a simple 'Hello World' script throws the following errors:
`Primitive reference catch is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:3:[15-26]
Primitive reference raise is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:6:[22-33]
Primitive reference test is unbound at ../../../usr/local/share/wake/lib/core/exception.wake:2:[15-25]`

How do I fix this?

**Comment by richardxia** [comment]
How did you install wake? `exception.wake` was removed between v0.14.0 and v0.15.0, so it should not be possible to run into the error that you are seeing on wake v0.15.0 and onwards.

**Comment by saurabhsingh-pvips** [comment]
I followed the steps prescribed in the readme. Checked out v0.15.0 before running `make` command. 
I downgraded from `v0.18.x`. Is it possible that `exception.wake` was a residue of previous install? If yes, can you let me know how to clean remove everything associated with `wake`?

**Comment by richardxia** [comment]
> If yes, can you let me know how to clean remove everything associated with `wake`?

Based on the other discussion thread in https://github.com/sifive/block-pio-sifive/issues/39, it looks like you've been installing wake into `/usr/local`. I don't think there's a clean way of removing everything that wake installs if you are installing it there, since that path is shared with any other packages that you may have installed there.

I would advise taking a look at what files wake copies when you run `wake install ...` and removing any files that get copied into those locations. You can install into a dummy directory instead of `/usr/local` to see what files it copies. Some files and directories that I think you would want to remove include /usr/local/bin/wake, /usr/local/share/wake, and /usr/local/share/doc/wake.

**Comment by saurabhsingh-pvips** [comment]
This worked. I sorted the files by date and removed the files associated with wake version other than `v0.15.x`. The wake command is running fine.

Also, the path `/usr/local` is default path set in `Makefile` of `v0.15.0`. This has been changed to `$HOME/stuff` in later versions.
