### ISSUE TITLE
getting some error with match operation 

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/wake#340]
I had already created one file existing.txt . and on this file, I am doing one operation, which is like following:
 for the following code:
<pre>global def safeRead _ = match (read (source &quot;existing.txt&quot;))
  Pass pdf = pdf 
  Fail _   = &quot;Read failed!&quot;
</pre>
If I run the command: <code>wake safeRead 0 </code>
Then it passes.
and then if I am trying to generalize it with following code:
<pre>global def safeRead filename = match (read (source &quot;filename&quot;))
  Pass txt = txt
  Fail _   = &quot;Read failed!</pre>
and then if I run the command : <code> wake safeRead existing.txt </code>
then it is showing some error like ,
<pre>Variable reference &apos;existing&apos; is unbound at &lt;command-line&gt;:1:[11-18]
Variable reference &apos;txt&apos; is unbound at &lt;command-line&gt;:1:[20-22]
&gt;&gt;&gt; Aborting without execution &lt;&lt;&lt;</pre>
So, why is it like this?

**Comment by richardxia** [comment]
There are two issues that I see:

1. Your Wake command is incorrect. The Wake command line interface interprets arguments as a Wake program. Therefore, `wake safeRead existing.txt` is being interpreted as a Wake program where you are calling the `safeRead` function on an argument. `existing.txt` is being interpreted as a function named `txt` being called on a variable named `existing`, since `obj.func` is equivalent to `(func obj)` in Wake. You need to quote the argument so that it is being passed in as a string, but you'll need to escape the quote characters so that your shell does not interpret them. You will need to write either `wake 'safeRead "existing.txt"'` or `wake safeRead \"existing.txt\"` to pass in a string to a function call from the command line.
2. In the Wake code itself, you have quoted the word `"filename"` in the match expression, which means that you are passing in the string `"filename"` rather than the variable `filename`. You should remove the quotes in that expression.

**Comment by ShraddhaDevaiya** [comment]
thanks,  for explanation !.  
this one <code>wake 'safeRead "existing.txt"' </code> is working. and yeah one more thing .In this  page : https://github.com/sifive/wake/blob/master/share/doc/wake/tour/tuples.adoc
tuple explanation is very good , but for running those example on command line , we are struggling ! 
means like in this case ,you provided the example , but  <code>wake 'safeRead "existing.txt"' </code> this thing you have not mentioned ,  so we tried by trial and error to run that.
so if possible in this <code>tuples.adoc </code> ,
can you please add those certain things if possible . so that we can get clear idea of that.
