### ISSUE TITLE
Support '?' early error return operator

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#382]
Something to allow early return of errors could be nice

https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html

**Comment by richardxia** [comment]
Actually, thinking about this a bit more, I think just having a `return` keyword at all would enable this, without needing the `?` short-circuit operator.

**Comment by terpstra** [comment]
Could you provide a code snippet of how this `return` keyword would be used?
Also, idea seems related to the `do` notation in Haskell. Or have I misunderstood?

**Comment by terpstra** [comment]
If I recall, the goal for do notation was to be able to make it easier to write the success path of a chain of Results. My guess is that a `return` is to serve a similar purpose?

Having a `return` and/or chaining the Pass cases like in a `do` necessarily serializes the operations. 

For example, the below code allows action1 and action2 to proceed in parallel:
```
def a = action1
def b = action2
match a b
  (Pass x) (Pass y) = ...
  _ _ = ...
```

In the next example, action1 must complete before action2 can start:
```
def x = match (action1)
  Pass x = x
  Fail f = return f
def y = match (action2)
  Pass y = y
  Fail f = return f
```

**Comment by terpstra** [comment]
I think we need a clear way to chain Result-returning functions together, which authors allows to clearly indicate which operations must wait for the success of prior steps.

FYI, if we define a good collection of Result-operators in this way, I will also definitely move into the anti-BadPath-er camp.

**Comment by richardxia** [comment]
Note, I wrote this before you made the last two comments.

> Also, idea seems related to the `do` notation in Haskell. Or have I misunderstood?

I would say that it doesn't have to be related to `do` notation, which implies a type of monadic syntactic sugar (with the `>>=` "bind" operator). A `return` statement in Wake would not need to unwrap monads to be useful, and it could just be a syntactic sugar for easier control flow.

> Could you provide a code snippet of how this `return` keyword would be used?

For example:

```wake
# Function with a return type of Result a Error
def myComplexCommand input =
  def result = failableCommand input

  def intermediateVal = match result
    Pass a = a
    Fail e = return e

  def intermediateVal2 = match (failableCommand2 intermediateVal)
    Pass a = a
    Fail _ = return "myCustomError".makeError

  def ret = finalFunc intermediateVal2
  Pass ret
```

that would be equivalent to:


```wake
# Function with a return type of Result a Error
def myComplexCommand input =
  def result = failableCommand input

  result
  | rmapPass (\intermediateVal
    failableCommand2 intermediateVal
    | rmapFail "myCustomError".makeError
    | rmap (finalFunc _)
```

**Comment by richardxia** [comment]
Also, [Rust's](https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html) and [Swift's](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html) `if let` expression would be nice for this.

**Comment by richardxia** [comment]
> I think we need a clear way to chain Result-returning functions together, which authors allows to clearly indicate which operations must wait for the success of prior steps.

In Haskell's `do` notation, I believe it actually tracks data dependencies. Rather than actually running things line-by-line imperatively, I think it only executes what is necessary in order to execute the next statement. Don't quote me on this, though, since I'm not a Haskell programmer.

**Comment by terpstra** [comment]
Haskel is lazy, so it automatically only runs things as needed. Wake is parallel, a property I'd like to maximize, so we need to have a more comprehensive solution. I think we could do something like this:
```
  def x ,& y = match x y # this goes in stdlib
    (Pass x) (Pass y) = Pass (x ,, y)
    (Fail f) _ = Fail f
    _ (Fail f) = Fail f
  def a = action1 ...
  def b = action2 ...
  def c = action3 ... # actions 1-3 proceed in parallel
  halfdef Pass (x,, y,, z) = a ,& b ,& c
  def d = action4 x y z # actions 4+ must wait for 1-3
  def e = action5 x y z
  def f = action6 x y z
  halfdef Pass (u,, v,, w) = d ,& e ,& f
  finalresult a b c d e f # this must wait for 1-6
```

The only new syntax we need here is `halfdef`. The idea here is that it allows you to use a falsifiable pattern, where it will simply return any unselected cases. In other words, it unrolls to this:
```
  def x ,& y = match x y # this goes in stdlib
    (Pass x) (Pass y) = Pass (x ,, y)
    (Fail f) _ = Fail f
    _ (Fail f) = Fail f
  def a = action1 ...
  def b = action2 ...
  def c = action3 ... # actions 1-3 proceed in parallel
  match (a ,& b, & c)
    Pass (x,, y,, z) =
      def d = action4 x y z # actions 4+ must wait for 1-3
      def e = action5 x y z
      def f = action6 x y z
      match (d ,& e ,& f)
        Pass (u,, v,, w) = inalresult a b c d e f # this must wait for 1-6
        Fail f = f
    Fail f = f
```

**Comment by terpstra** [comment]
(Obviously halfdef is a terrible name)

**Comment by terpstra** [comment]
I'll note that `?` is still up for grabs lexically. Rust only runs one expression at a time, so it's relatively easy to say "return early". I don't see how to get such a frictionless an operator, without sacrificing parallelism. We need to have a clearly defined sequence point, before which everything is parallel and independent and after which, something has completed. Perhaps `when` or `then` could be the keyword:
```
def a = action1 # actions 1-3 launch in parallel
def b = action2
when Pass c = action3 # everything after this line must wait for action 3 to complete
def d = action4
def e = action5
when Pass (a, e) = a, & e # everything after this line must wait for actions 1+5 to complete
...
```

**Comment by terpstra** [comment]
@albertchen-sifive @jackkoenig You guys probably have an opinion.

I do think handling of Option and Result needs some form of syntactic sugar to make things easier.

Hmm. Maybe we don't even need the tuples for waiting. How about this:

```
def a = action1
def b = action2
def c = action3
when Pass c
def d = action4 c
def e = action5
when Pass a
when Some b
def f = action6 a b c
when Pass f
...
```

This desugars to:
```
def a = action1
def b = action2
def c = action3
match c
   Fail f = f
   Pass c =
     def d = action4 c
     def e = action5
     match a
       Fail f = f
       Pass a =
          match b
             Fail f = f
             Pass b = 
               def f = action6 a b c
               match f
                  Fail f = f
                  Pass f = f
                     ...
 ```

**Comment by terpstra** [comment]
Adding this kind of `when` would be relatively painless, actually.

**Comment by terpstra** [comment]
We could also allow for a short-hard version of `when` combined with `=`:
```
def a = action1
def b = action2
when Pass c = action3
def d = action4 c
def e = action5
when Pass a
when Some b
when Pass f = action6 a b c
...
```

To be clear, we still encourage 'action1-6' to use a `|` style in their definitions. The recommended coding style becomes:
- give every failable computation it's own `def` pipeline
- allow as many things to run at once as possible
- use `when` to sequence failable steps
- don't try to shove everything into a single pipeline (looking at you @albertchen-sifive !)

**Comment by jackkoenig** [comment]
This looks sensible to me. Composition of Results has been a pain so I think having special `do` or `for`-like syntax for desugaring would be really great.

Would this be user extensible? In that it works for any data with 2 (or more?) types?

```
export data EitherOption left right =
  Left left
  Right right
  Neither
```

Then I could desugar
```
def a = eitherOptionReturningThing
when Right a
def b = action a
```
Into
```
def a = eitherOptionReturningThing
match a
  Left l = Left l
  Neither = Neither
  Right a =
    def b = action a
```

**Comment by jackkoenig** [comment]
I'll note that the variable shadowing without tabbing is a little unintuitive from me (with my Scala background), might it be better to just do:
```
def a = action1
def b = action2
def c = action3
when Pass d = c
def e = action4 d
```

**Comment by terpstra** [comment]
re: user-defined types, yes, my proposal would work with your EitherOption type. It just reconstructs all cases that were not in the `when` clause. It is a bit annoying to me that you cannot mix `when Pass` and `when Some` in the same function. Maybe there is a sneaky way to achieve this?

re: name shadowing, my proposal allows you to do `when Pass d = c` if you choose. I just thought it would be nice to allow a short-hand where you leave off the `=`.

**Comment by terpstra** [comment]
The main pain point in implementing this is that this does not type check:
```
def foo = Pass 5
def bar = match foo
  Pass 6 = Pass "xx"
  z = z
```

You actually have to write `Fail z = Fail z`. This makes it a bit tricky to desugar `when` before I have resolved variable references/packages. I guess it would need to desugar to a special kind of `otherwise` clause which I then desugar further later.

**Comment by terpstra** [comment]
Another random thought. `when` is just `def` which has a defined behaviour for falsifiable pattern matches. We could just modify `def` to act the way we are discussing `when` to act. Is that a bridge too far?

**Comment by terpstra** [comment]
Should `when` is legal at the top-level?

**Comment by terpstra** [comment]
Nevermind. That was a stupid question. `when` only LOOKS like `def`. It replaces the body of a block. The top-level has no body. Therefore, it cannot have a `when`.

**Comment by terpstra** [comment]
The short-hand syntax (where you leave off the '=') is not great. What if the pattern has more than one term in it; eg:

```
data MyData =
  Good Integer Integer
  Bad String
```

Then this would be super confusing if there was no `=`:
```
def a = action1 # returns MyData
when Good x y = a
```

**Comment by richardxia** [comment]
> We need to have a clearly defined sequence point, before which everything is parallel and independent and after which, something has completed.

Just wanted to explicitly acknowledge this point.


This has also made me think that this `when` statement you are talking about really reminds me of the `async/await` syntax that was added a few years ago to [JavaScript](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await#Rewriting_promise_code_with_asyncawait) (and [Python](https://www.python.org/dev/peps/pep-0492/) and [Rust](https://rust-lang.github.io/async-book/01_getting_started/04_async_await_primer.html) have also added them recently as well). The `await` keyword is analogous to your `when` keyword, and the `async` keywords in those languages are meant for opting into an asynchronous result (a Future), whereas in Wake everything is naturally a Future.

Your syntax here really is just a combination of `await` plus pattern matching. I wonder if it'd be a good idea to reuse those keywords here, since a number of languages have adopted them. It looks like they even [originate from C#](https://softwareengineering.stackexchange.com/questions/377464/who-did-async-await-first) in 2012, but based on [syntax from F# in 2010](https://docs.microsoft.com/en-us/archive/blogs/dsyme/introducing-f-asynchronous-workflows), which is a more ML-y way of doing it.

**Comment by richardxia** [comment]
Oh, what if you also tried something like [Swift's `guard-let-else`](https://thatthinginswift.com/guard-statement-swift/) expressions? You could possibly handle a user-defined pattern match with the `else` clause, requiring a pattern match on the remaining patterns. For @jackkoenig's example, this could look like:

```wake
export data EitherOption left right =
  Left left
  Right right
  Neither

def a = eitherOptionReturningThing
await def Right someThing = a else match
  Left a = Fail a.format.makeError
  Neither = Fail "Expected a Right".makeError
def b = action a
```

**Comment by terpstra** [comment]
While I see what you are trying to achieve (a systematic way of unifying the types to Result), I think it would be more readable to do this:

```
export data EitherOption left right =
  Left left
  Right right
  Neither

def eitherToResult = match _
  Right x = Pass x
  Left a = Fail a.format.makeError
  Neither = Fail "Expected a Right".makeError

def a = eitherOptionReturningThing
await def Pass someThing = a.EitherToResult
def b = action someThing
```

**Comment by terpstra** [comment]
FYI, I just implemented `when` (https://github.com/sifive/wake/pull/383) so we can try it out.

**Comment by richardxia** [comment]
> While I see what you are trying to achieve (a systematic way of unifying the types to Result), I think it would be more readable to do this:

Yeah, I'd agree that what you have is more readable. Then, are you thinking that you'd only allow pattern matching on ADTs that only have two constructors?

> ... and we should have someToResult in the standard library.

Yes, and I believe it's called `getOrFail[Fn]`.

---

As a side note, I know this might be a small detail, but I would strongly argue for using a different keyword than `when`. `when` is used by Perl, Ruby, and probably a few other languages in `switch` statements. It's also used by Chisel for something like an `if` statement.

**Comment by terpstra** [comment]
The current implementation proposal works on ADTs with any number of constructors (including 1). It just creates identity functions for all the un-matched cases.

**Comment by terpstra** [comment]
The reason I like `when` is BECAUSE this is like a case in a switch statement. Plus it also suggests order.

**Comment by terpstra** [comment]
I think await is different than this new keyword. Wake has an implied await around (almost) every application of a primitive function to a value. The core functionality we are looking to get out of this new keyword is the ability to have a partial match function, to ease working with Result/Option. The fact that it acts like a sequence point is just a symptom of the act of calling `match` on the argument.

**Comment by terpstra** [comment]
Another subtly, `when` does not actually cause it to wait for the expression to "complete". It waits for the pattern to be resolved. That means that if your action succeeds before it has (for example) completely filled in the result list, statements after then `when Pass` will execute (since it is now known that the action succeeded). Wake will still naturally block whenever the result list is used in a way that forces it to wait.

**Comment by albertchen-sifive** [comment]
thoughts on having a non-sequential version of this? like sometimes I do this because I don't want to serialize a bunch of jobs:
```
match res1 res2 res3 ...
  (Fail e) _ _ ... = Fail e
  _ (Fail e) _ ... = Fail e
  ...
  (Pass p1) (Pass p2) (Pass p3) ... = resultFn p1 p2 p3 ...

**Comment by richardxia** [comment]
> thoughts on having a non-sequential version of this? like sometimes I do this because I don't want to serialize a bunch of jobs:

If I understand @terpstra's description of how his `when` statement works, then you could write your example as:

```wake
when Pass p1 = res1
when Pass p2 = res2
when Pass p3 = res3
resultFn p1 p2 p3
```

Your example in inherently "sequential" because you have an ordered handling of the failures, where res1's failure has highest priority and so on and so forth. The actual execution of res1, res2, and res3 is in parallel, since all three of them are placeholders for values.

In both your example and the future `when` syntax, res1, res2, and res3 must all run.

--- 

> The reason I like when is BECAUSE this is like a case in a switch statement. Plus it also suggests order.

I'm still not sure if I agree that this is like a case in a switch statement, since Wake already has its own version of that in the form of the `match` expressions. Clearly there is a difference in semantics between `match` and `when`, but I don't think that is immediately evident from the keyword name.

> I think await is different than this new keyword. Wake has an implied await around (almost) every application of a primitive function to a value. The core functionality we are looking to get out of this new keyword is the ability to have a partial match function, to ease working with Result/Option.

This makes sense to me, and I agree now that `await` would be an inappropriate name. That said, I still don't feel like `when` is that clear, especially when you have an ADT with more than two constructors.

---

I've thought a bit more about why I feel the >2 ADT case feels strange to me, and I think it's more related to having type parameters rather than just ADTs. `Option a` has a single type parameter, and `Result p f` has two type parameters, where each type is exclusively used by one of the two constructors. When we only consider the cases of `Option` and `Result`, there is a natural and intuitive formation of return types, even if the `when` statements match against different types.

For example, a Wake function could easily chain `when` statements that match `Result a' f`, where `a'` can be different for each `when` statement as long as the `f` type is the same. In fact, the final return type of the function does not have to be any of the `a'`, since it is just what you "return" at the end, which is equivalent to how Haskell's `Monad` `return` actually works at the end of a `do` block.

I think this monadic property is actually somewhat important for using `when` with user-defined types, since there needs to be a natural and intuitive `return` definition. In Haskell, you must explicitly define this by implementing the `return` or `pure` function for that Monad; in Scala you implicitly define this in the type signature of `flatMap`.

**Comment by richardxia** [comment]
I still feel that your `when` statement is semantically equivalent to a [`guard` statement in Swift](https://docs.swift.org/swift-book/LanguageGuide/ControlFlow.html#ID525). If you don't want the `else` clause to be mandatory, I think that's fine, since you've already shown me [above](https://github.com/sifive/wake/issues/382#issuecomment-603564145) that you can just to a manual pattern match above it.

**Comment by albertchen-sifive** [comment]
> If I understand @terpstra's description of how his `when` statement works, then you could write your example as:
> 
> ```
> when Pass p1 = res1
> when Pass p2 = res2
> when Pass p3 = res3
> resultFn p1 p2 p3
> ```

> In both your example and the future `when` syntax, res1, res2, and res3 must all run.

I might be misunderstanding, but rewriting as 
```
match res1
  Fail e = Fail e
  Pass p1 = match res2
    Fail e = Fail e
    Pass p2 = match res3
      ...
```

is different from
```
match res1 res2 res3 ...
  (Fail e) _ _ ... = Fail e
  _ (Fail e) _ ... = Fail e
  ...
  (Pass p1) (Pass p2) (Pass p3) ... = resultFn p1 p2 p3 ...
```

because in the first example `res2` and `res3` never get run if `res1` fails, whereas they all get run in parallel unconditionally in the second. like I was thinking that wake could just infer the "flattest" match thingy that would let as much stuff run as possible rather than having to order your `def`s and `when`s? not sure if I'm making any sense

**Comment by richardxia** [comment]
> because in the first example `res2` and `res3` never get run if `res1` fails, whereas they all get run in parallel unconditionally in the second. like I was thinking that wake could just infer the "flattest" match thingy that would let as much stuff run as possible rather than having to order your `def`s and `when`s? not sure if I'm making any sense

My understanding is that even in the second example, `res2` and `res3` will be run in parallel with `res1`, regardless of whether `res1` fails? Let me try rewriting in a slightly different way:

```wake
res1 = failableAction arg1
res2 = failableAction arg2
res3 = failableAction arg3

# when-style
when Pass p1 = res1
when Pass p2 = res2
when Pass p3 = res3
resultFn p1 p2 p3

# match-style
match res1 res2 res3 ...
  (Fail e) _ _ ... = Fail e
  _ (Fail e) _ ... = Fail e
  ...
  (Pass p1) (Pass p2) (Pass p3) ... = resultFn p1 p2 p3 ...
```

In think in both cases, the `failableAction`s are all running concurrently. @terpstra, can you comment? It's clear that we don't have a strong understanding of the execution model of Wake.

**Comment by albertchen-sifive** [comment]
I meant for `res`, `res2`, `res3` to be placeholders for an arbitrary expression. so yes in your case they are the same but what I wanted to avoid was
```
when Pass p1 = failableAction arg1
when Pass p2 = failableAction arg2
when Pass p3 = failableAction arg3
resultFn p1 p2 p3
```
being rewritten to:
```
match (failableAction arg1)
  Fail e = Fail e
  Pass p1 = match (failableAction arg2)
    Fail e = Fail e
    Pass p2 = match (failableAction arg3)
      ...
```
I would like for the `when`s to not be predicated on each other because there is no actual data dependency between them. then we wouldn't have to worry about defining `def`s before `when`s to make them run in parallel

**Comment by terpstra** [comment]
So ... you are both right!

Albert is right that in:
```
match (failableAction1 arg1)
  Fail e = Fail e
  Pass p1 = match (failableAction2 arg2)
    ...
```
failableAction2 will not run if failableAction1 fails.

Richard is of course right that if you do:
```
def res1 = failableAction1 arg1
def res2 = failableAction2 arg2
match res1
  Fail e = Fail e
  Pass p1 = match res2
  ...
```
... then both failable actions execute unconditionally.

I think you guys only disagreed because Richard thought Albert's `res1` was a variable reference and Albert meant it was an expression with side-effects.

**Comment by terpstra** [comment]
To address your concern, though, Albert:

```
when Pass (a,, b,, c) = (action1 arg1,& action2 arg2,& action3 arg3)
```
... would do what you want. However, I do think explicitly giving each action would make the code more readable.

**Comment by terpstra** [comment]
For that matter, so would this:
```
when (Pass a,, Pass b,, Pass c) = (action1 arg1, action2 arg2, action3 arg3)
```

**Comment by terpstra** [comment]
@richardxia I mostly agree with your Monad commentary. `when` is only useful on types where the not-selected cases have a simple enough type that they can be unified with each other and the eventual result.

How does this translate into a concrete proposal for a `when` alternative, though?

**Comment by terpstra** [comment]
The proposed `when a = b` is like this in swift: `guard let a = b else { return b}`. 

Adding the option to specify an `else`-like thing other than the current implied "return b") is useful. That would make it easier to unify the failure results. I think `guard` is also a perfectly acceptable choice for the keyword if `when` is considered terrible.

However, I don't see that replacing `when` with `guard` would materially impact Matthew's complaint. You would still (in Swift) need to write `guard .pass(let a) = b` to deconstruct `b`.

**Comment by terpstra** [comment]
Concretely, I think we are talking about this:
```
def a = action1 ...
def b = action2 ...
def c = action3 ...
guard Pass x = a
guard Some y = b else Fail "action2 returned None".makeError
...
```

**Comment by terpstra** [comment]
How about `require` + optional `else` as the keyword(s)? I find that much descriptive than `guard`. My only complain is that it's a lot more typing than `when`.

**Comment by richardxia** [comment]
Just putting down an example so that I can see it here:

```wake
def a = action1 ...
def b = action2 ...
require Pass x = a
require Some y = b else Fail "action2 returned None".makeError
def c = action3 x y
```

I think I agree that `require` is a better keyword than `guard`, and I don't mind typing `require`, since it's more explicit and less commonly-used keywords deserve more visual attention.

**Comment by richardxia** [comment]
Oh, also, will the `else` clause allow you to pattern match on the other cases? In the case of `Option` it's not useful, but in the case of `Result` it'd be useful to not have to handle the `Some` case within the `else` clause if you wanted to slightly modify or wrap the underlying `Fail` before returning it.

**Comment by terpstra** [comment]
My thinking does like this: we have `match`. It's very good for handling all the cases. The reason we are adding `require` is to make it easier to handle the 'common case'. However, `require` without an else has no way to convert the type of the uncommon cases. Adding an `else` gives you the opportunity to do that conversion and keep the error message together with the requirement failure. 

To me this suggests: you can always call `match` either in the else clause (or even better in a helper function).

**Comment by terpstra** [comment]
The main counter argument I have against this 'use a helper function' approach is that it makes it cumbersome to convert the type of the `Pass` case.

Eg:
```
def wrapFail message = match _
  Fail (Error why stack) = Fail (Error "{message}: {why}" stack)
  Pass _ = panic "unreachable" # this sucks
```

**Comment by terpstra** [comment]
The counter-counter-argument to this is that you should do this instead:
```
def wrapFail message = match _
  Fail (Error why stack) = Fail (Error "{message}: {why}" stack)
  Pass ok = ok

def work _ =
  def a = action1 ...
  def b = action2 ...
  require Pass x = wrapFail "gcc broke" a
  ...
```

**Comment by terpstra** [comment]
Once the keyword was called `require`, it suddenly became obvious to me how useful this is to use with literals in the pattern:
```
def foo = x
  require Pair y 8 = x else 1
  y + 2
```

**Comment by mmjconolly** [comment]
Can you please add something about `require` to the documentation.

As an exercise, I'll make some purposefully uneducated guesses about what someone could interpret this example as, so you get a idea of where I'm coming from
```
def foo = x
  require Pair y 8 = x else 1
  y + 2
```
foo is a function that:
1.  ignores `x`, returns `y+2`, and will panic if `x else 1` is not a pair
2. returns `x`, ignores the next two lines
3. `require` is a function that takes `x` and `Pair y 8` and is assigned `x else 1`

**Comment by terpstra** [comment]
I can add something to the quickref, sure.

FYI, I don't think examples like the one you quoted (or even most of the examples I posted) are going to be the common use-case of this keyword. I posted these examples to purposely demonstrate the full applicability of the syntax.

The most common use will, by far, I think look this:
```
require Pass value = resultOfAction
... stuff using value ...
```

**Comment by terpstra** [comment]
Actually, I think what we need is a new entry in tour/ that describes pattern matching in general. We have almost no documentation about how `match` works.  Or how `def` works, for that matter.
