### ISSUE TITLE
Is it possible to export the job/hash/database/sandbox sub-system to other languages?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#402]
If wake has a clear library interface of the job and sandbox system, it may can be ported to other languages.

**Comment by terpstra** [comment]
I don't understand what you are requesting, here. In any case, I do have plans to revamp the way this part of wake works before 1.0. I'm not sure if this will come before or after 1.0, but being able to use wake to save/restore expensive computations used in scala is something I would like to make possible at some point.

**Comment by davidmlw** [comment]
I mean, with some interface like SWIG, wake may be exported to other languages, such as python, ruby or haskell. The benifits would use other languages wheels for package, list, string, namesapce, etc.

**Comment by terpstra** [comment]
We've been talking about enhancing the build to work a bit more like llbuild underneath. That would make it possible to implement build rules in other languages.

I have to say I am torn, though. In my mock-ups of writing rules in at least C++ and scala, it is much higher friction/effort to do both simple and complex build rules. Wake is a build DSL. This disparity will likely only increase with time. I think the main value of this approach is actually:
- using other build DSLs (like make/ninja/etc) seamlessly in the same flow
- being able to (at relatively high effort) reuse the build system to cache expensive computations done as steps in other languages (in particular, chisel circuit minimization)

Unfortunately, there are things that are only possible to automate when you control the entire language runtime and compiler. For example, current wake can automatically extract all available parallelism from your code (not just trivial stuff like parallel function calls, either, but ALL of it).
The next version of wake will also be able to automatically cache computation, even if an input/output was a function. These not things you can do without either explicit annotations in the API (and trust that users do it correctly) or complete control over the compiler.

That said, if you are just looking for better string or list manipulation, perhaps you can enumerate your pain points and we can address them. Regarding package/namespace, wake now has support for this. We'll see how that works out.

**Comment by mmjconolly** [comment]
(Slight topic hijack) As you've mentioned string manipulation, I can think of some missing functions you'd expect from a stdlib string library (without using regexps)
- Contains substring
- Has/remove prefix/suffix
- Character at index
- Join
- Character replace (the shell `tr` style) 
- Substring replace
- Split into list, by separator string
- Trim leading/trailing whitespace

**Comment by terpstra** [comment]
I think we have most of these by virtue of regular expressions. Perhaps helper functions would be in order, though:

```
def strContains substr str =
  def regex = `.*`, quote substr, `.*`, Nil
  matches regex.regExpCat str
def hasPrefix prefix str =
  def regex = quote prefix, `.*`, Nil
  matches regex.regExpCat str
def removePrefix prefix str =
  def regex = `^`, quote prefix, Nil
  replace regex.regExpCat "" str
def join = cat # or do you mean something else?
def substrReplace = replace # or do you mean something else?
def splitIntoList = tokenize # or do you mean something else?
def trimHead str = replace`^[ \t\n\v]` "" str
def trimTail str = replace `[ \t\n\v]*$` "" str
```

I'm not sure how best to implement 'tr style' replacement. Is this even a good API to have? Most of the time I've seen it used, it's been to capitalize/lowercase strings, and we have functions for that. If this is deemed must-have, I think it would have to be written in C++ and made into a primitive.

I've tried to avoid encouraging use 'strlen' and 'substr' (charAtX) functions which use absolute indexes. What constitutes a character is extremely murky in Unicode, and people don't usually realize how fraught it is. Are indexes by byte, code-point, or glyph?

**Comment by terpstra** [comment]
Now that I've written them, I wonder if these functions actually improve readability. One the one hand, they relieve the user of having to know regular expressions (which not everyone does). On the other hand, for those who do know regular expressions, the proliferation of string functions is somewhat analogous to the omap/rmapPass/etc fiasco. Now you need to memorize a ton of two-liner functions to be able to read code that uses them.

ie: if you have a concrete prefix to remove, then ```
replace `^abc` "" str
```
is similar typing and less for me to memoize than a family of `removePrefix "abc" str` functions.

**Comment by mmjconolly** [comment]
I'm not too concerned about exactly which string operations are available or how they work internally, so long as commonly used ones are there.

The omap/rmapPass/etc was an issue for a different reason though, control flow and error handling, and that they didn't have descriptive names.

This is more an argument about read-mostly ergonomics and making simple operations simple.
Focusing on this example,
```
(1) replace `^abc` "" str

(2) removePrefix "abc" str
```
I very much prefer (2), to me it's much easier to read as it tells you the intent in English.
Regardless of if someone does or doesn't know regexps, they shouldn't be *required* to know them to do something as basic as a string operation.

**Comment by mmjconolly** [comment]
> Now you need to memorize a ton of two-liner functions to be able to read code that uses them.

I also want to point out that most people who read wake code will have not memorized many, if any, wake functions as they're usually just trying to do some other task and don't want to think about the build system at all.

**Comment by richardxia** [comment]
> or glyph?

There is no way to reliably do it by glyph, since the definitions of the glyphs may change over time, and there are very complex glyph rendering rules for non-Latin-based languages. Glyphs are also dependent on the font used, since even in English we have [ligatures](https://en.wikipedia.org/wiki/Orthographic_ligature) (one of the most common is combining an "f" and an "i" into a single glyph). There's even a [CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures) that lets you enable/disable ligatures in an HTML element!

---

Font-encoding and typography nerding out aside, I think given Wake's intended domain of interfacing with command line programs and filesystems, I think it's a bit problematic that it interprets Unicode at all given that none of the Linux APIs specially handle Unicode. The overwhelmingly majority of Wake strings are used for either describing file paths or command line arguments, and in both of those cases the true APIs are byte arrays. It _is_ legal to create a file whose name is not a valid UTF-8 encoded string.

Outside of Wake, I've had first-hand experience with issues with Unicode normalization on filesystems differing between Windows and Mac, where difference sequences of Unicode code points can combine into the same glyph, and Windows and Mac have _different_ rules when it comes to normalization.

Also, what if I need to shell out to a legacy program that only accepts [latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) or [Shift_JIS](https://en.wikipedia.org/wiki/Shift_JIS) command line arguments?

**Comment by terpstra** [comment]
Actually, some newer filesystems ARE unicode in their filenames and reject illegal / ambiguous unicode for security reasons.

**Comment by terpstra** [comment]
FYI, there is a standard for unicode normalization. If Windows and Mac do it differently, one of them is wrong, and a bug should be filed. Also, wake DOES actually operate on raw binary strings. One of the differences between 'abc' and "abc" is that the former is not normalized (I intend to document this in the near future, but it has always been true). My goal with using regular expressions was to make it difficult to shoot yourself in the foot with Unicode, because a regexp cannot split an expression at a granularity below its own tokens. That's how it keeps you safe when handling Unicode, even though wake itself barely does anything with Unicode (other than normalizing "abc" literals).

**Comment by terpstra** [comment]
@mmjconolly I think I mostly agree that if the function name is obvious enough (like `removeStringPrefix`), then you don't need to have it memorized to read the code.

**Comment by colinschmidt** [comment]
The original request is not something that we plan to support.
The tangential request about string functions is something we plan to address in wake-extras.
