### ISSUE TITLE
How to use job ID to inspect the job information

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#404]
`makePlan | runJob ` gets a job ID, it is better to have inspecting methods to use this ID. Like:
`wake --job-report <ID>`

Like wit, is it possible to have a `inspect tree`?
wake --inspect-tree to get a Job dependency graph, with job as node and path as edges.

**Comment by terpstra** [comment]
There is a shell command in `scripts/digraph` you can run which creates this picture for the whole build. However, there is so much information in these pictures that they are pretty much useless. Issue #281 is asking for a better way of visualizing this information. There is a much easier feature to support, though, which you mentioned: inspect the database by Job-ID instead of input/output file.

**Comment by terpstra** [comment]
I always considered the Job-ID to be more-or-less opaque information that no one would be interested in as a query key. About the only way to learn about the Job-ID is by running 'format' on the Job and saving or printing the result.

How would you use this feature?

**Comment by davidmlw** [comment]
In my opinion, printing formatted job info is convient, but should be compact. An ID is still useful as a handle when the user wants to inspect more information.

**Comment by terpstra** [comment]
Ok.

**Comment by richardxia** [comment]
I would also find this useful. One of my use cases is that I often run `wake --failed` or `wake --last`, but if I continue to run commands new, it'll change the results of those commands, and it becomes more difficult to keep track of a particular Job that ran in the past.

In addition, `wake -v --failed` or `wake -v --last` dumps a ton of output, when oftentimes I just want the verbose output for a specific job. Finally, sometimes the visible/output file lists themselves are quite large, and I just want `wake --failed` and `wake --last` in order to identify a particular previous run, and it'd be nice to use the Job ID it prints out as a handle to the Job that I can refer to within a specific work session.

**Comment by terpstra** [comment]
Blast. I overlooked this issue when preparing 0.19.0. I will try to get it in for the next release.
