### ISSUE TITLE
How to test a path being a file or a directory?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#425]
lib/system/path.wake seems have no relative API for this.

**Comment by terpstra** [comment]
Yes. A good point.

At one point I wanted to require all Paths for directories to end with a '/'. This would have the benefit of simplifying the fix to #49. Since manipulations on paths happen in String form, you would not be able to tell the difference there until you turned it into a Path. Actually, this approach may also help with #390. The rules there could be that Paths are fully reduced to canonical form (which includes a trailing '/' for directories) as opposed to Strings, which are what simplify operates on.

**Comment by richardxia** [comment]
> The rules there could be that Paths are fully reduced to canonical form (which includes a trailing '/' for directories) as opposed to Strings, which are what simplify operates on.

This could be problematic and cause a bit of confusion to tools or programs that make certain assumptions about directory paths. For instance, both `cp` and `rsync` do different things based on whether a trailing slash is present: https://stackoverflow.com/a/24925767/7433423

In addition, there is an minor issue of keeping the trailing slash when putting directory paths in certain environment variables such as `PATH`, where it's customary to _not_ end the path in a trailing slash, and therefore when tools make use of those variables, they tack on an additional slash before adding their own paths. We may run into canonicalization issues if you have two different strings like `foo/bin/bar` and `foo//bin/bar`.

Yes, I know on the Wake user side of things we can always append or strip trailing slashes when we extract a `String` out of a `Path`, but it could be confusing to always canonicalize directories to have a trailing slash.

**Comment by terpstra** [comment]
I don't find the 'cp' or 'rsync' examples very compelling. Because the trailing '/' matters there, you would have to handle the Path to command-line conversion carefully no matter which way we represent directories in a Path.

I agree that a trailing slash might be a bit obnoxious in some cases, like PATH, as you mentioned. However, we could add a different 'getPathName' accessor to make this easy.

Wake already resolves 'foo//bin/bar' to 'foo/bin/bar' when you simplify in String-land. That carries over to Paths currently as well.

I'm not sure what's more confusing: 'foo/bar' being either a directory or a file vs. 'foo/bar/'. Since the underlying APIs just sort this out automatically for you (Paths are always job outputs), there is no way for a user to screw up construction of a Path, which is always produced in canonical form. As a consumer of the Path, I feel it would actually be helpful to see the trailing '/' or not.

**Comment by richardxia** [comment]
> Because the trailing '/' matters there, you would have to handle the Path to command-line conversion carefully no matter which way we represent directories in a Path.

Although I agree, I think there is still something to be said about having a default behavior that does not match any other tool. To me, it would be confusing to have `mkdir "mydir"` return `Path "mydir/"` (or more accurately, to have `mkdir "mydir" | getPathName` return `"mydir/"`).

> As a consumer of the Path, I feel it would actually be helpful to see the trailing '/' or not.

I think we should draw a distinction between how things are displayed to a human (e.g. with `format`) vs. things that are part of actual APIs. I agree that it would be helpful as a human to be able to visually distinguish a directory Path from a file Path, but to have that actually bleed into `getPathName` would be more confusing to me. I would have less of an issue with having the default string formatting of a `Path` print out a path type as well.

Separately, I think things also get a bit confusing with symlinks. Is a symlink to a directory treated as a file or a directory? What if initially create a symlink to a file, but then I swap out the thing that the symlink pointed to with a directory? In the latter scenario, the symlink itself is untouched.

**Comment by terpstra** [comment]
I think what a human sees should match what the API sees, wherever possible. FYI, I have seen this behaviour with paths using a trailing slash in other tools, which is where I got the idea from. Can't recall which tools atm, though. Also, most unix commands will accept a trailing slash for directory inputs.

So, symlinks in wake are just completely broken right now. If we dealt with them well, I would say that a Path should have all symlinks resolved. The symlink ('foo' -> 'bar/') itself is a file (no '/'), but if you have any outputs inside that symlink, they use the full name 'bar/zzz'.
