### ISSUE TITLE
Symlinks to cover missing .fuse/ paths?

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#439]
When we have a build that embeds a `workspace/.fuse` path into a build artifact, that path doesn't resolve post-build.

A program trying to resolve a path like `/home/user/workspace/.fuse/5555/build/foo` is really trying to resolve `/home/user/workspace/build/foo` post-build.

Could we leave behind a directory-symlink as `fuse-wake` is exiting? 
Example: `/home/user/workspace/.fuse/5555 -> /home/user/workspace`

While it doesn't solve the underlying issue, perhaps it could paper-over some of the pain points of the situation

**Comment by terpstra** [comment]
The 5555 here is the process ID. So, unfortunately, those values get reused during a build. ie: two jobs might use the same ID.

Also: I would rather we solve this by using unshare. I was originally planning on bind mounting the fuse jail to /build and then running the build there. Do you think we could somehow play tricks so that for the user /build points back at their workspace? I'd like to use /build so it is the same output regardless of who built something (shared caching). However, as you note, it is helpful to be able to introspect the artifacts post-build.

**Comment by richardxia** [comment]
Even if the process ID is reused, all of the directories within the .fuse/ directory should point to the workspace root, so it shouldn't matter if there's a duplicate, right? This suggested workaround is mostly meant to be a quick to implement, easy to remove temporary measure until we have more time to implement a more complete solution such as the bind mounting idea you described.

**Comment by mmjconolly** [comment]
I agree that unshare/namespacing is a good way forward generally, but I do feel that we need to consider the short term too.

We have support load helping people who don't understand why some programs they run that consume build artifacts containing paths that don't exist.

I have some questions (where I presume we won't have unshare for enough time that it makes sense to implement a stopgap):
* Can you describe what the PIDs are used for in the fuse-wake/fuse-waked/wake interaction?
* What was the reasoning behind having workspace/.fuse/ as a mountpoint, what sorts of problems to we get if we just mount on top of workspace/ itself (thus keeping the paths the same)?
* If we must have a PID, could we suffix it something to take worries about pid_max rollover off the table, perhaps the process start time ticks (from /proc/$pid/stat)
* If we allow mounts on top of a pre-existing .fuse directory and we stick with only using PID for the id, can we pre-populate the directory with all possible pids from 0 to /proc/sys/kernel/pid_max then mount over the top of it thus hiding the symlinks from the sandboxed process

**Comment by mmjconolly** [comment]
> Do you think we could somehow play tricks so that for the user /build points back at their workspace? I'd like to use /build so it is the same output regardless of who built something (shared caching). However, as you note, it is helpful to be able to introspect the artifacts post-build.

An option is to provide a script/cmd that invokes a shell which has unshare / bind mounted `$HOME/workspace/build` on top of `/build` such that only inside that shell session they see the build paths as the same

**Comment by terpstra** [comment]
I like your 'restore environment' script idea. Sort of like how you can get a 'rerun' the job description out of wake, but for the environment.

**Comment by terpstra** [comment]
> We have support load helping people who don't understand why some programs they run consume build artifacts containing paths that don't exist.
> I have some questions (where I presume we won't have unshare for enough time that it makes sense to implement a stopgap):

I understand. I would love to promise to get to work on this in a few days, but I can't yet.

> * Can you describe what the PIDs are used for in the fuse-wake/fuse-waked/wake interaction?

It's the PID of the fuse-wake process, which then execs the build task. Come to think of it, this is not particularly safe, because that process might exit while children are still active on the .xyz directory. The .xyz directory won't go away since all the children hold a 'keep-alive' file descriptor for the directory, but if the kernel reuses the PID right away, that could be an issue.

> * What was the reasoning behind having workspace/.fuse/ as a mountpoint, what sorts of problems to we get if we just mount on top of workspace/ itself (thus keeping the paths the same)?

Well, without unshare, you can't do that. With unshare, you could bind mount it over the workspace. There are several problem with mounting it on top of workspace/:
1- it won't work if any process is active in that directory on some OSes (maybe linux too?)
2- we need a different filesystem subset for each job (the visibility list)
3- the FUSE daemon still needs access to the original files which would be hidden by the mount
... probably more I have forgotten.

If you do an unshare, however, the FUSE daemon is running in a different namespace, so 1+3 are sorted out. Also, if there is one unshare per job, 2 is sorted out as well.

> * If we must have a PID, could we suffix it something to take worries about pid_max rollover off the table, perhaps the process start time ticks (from /proc/$pid/stat)

I think @richardxia is correct that conflicts don't actually matter, because all the symlinks point to the same place anyway.

> * If we allow mounts on top of a pre-existing .fuse directory and we stick with only using PID for the id, can we pre-populate the directory with all possible pids from 0 to /proc/sys/kernel/pid_max then mount over the top of it thus hiding the symlinks from the sandboxed process

This would probably work.

**Comment by terpstra** [comment]
Fixed by #444
