### ISSUE TITLE
Mechanism to at-runtime include/exclude wake code

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#442]
Say if we have 2 repositories, `product-foo` and `product-baa`, where product-baa forked away from product-foo a long time ago, they likely have common symbol names with potentially conflicting function implementations.

When trying to re-consolidate the two codebases it's often useful to place them together in the one repository before beginning an incremental refactor.

With wake searching for `*.wake` files we don't have a way to try to execute only product-foo or only product-baa wake rules.
We could hack something together adding/remove .wakeignore entries but it would be nice if we could have a bit more control at the wake command line.

**Comment by terpstra** [comment]
You're imagining something like `wake --ignore product-foo ... rest of args`? Like a command-line-specified additional .wakeignore line? Seems reasonable. I guess using .wakeignore here is awkward because it would have had to be in the workspace root?

Would the package system have helped here? ie: did `product-baa` rename its wake package when it forked?

**Comment by terpstra** [comment]
Are you still interested in this? Or is the 'write a .wakeignore file' solution before invoking wake good enough?

**Comment by mmjconolly** [comment]
I think we'll need something like this, but not sure on the actual requirements at this stage, `product-baa` from above is apparently changing its dependency tree so I think the _immediate_ need goes away

**Comment by terpstra** [comment]
Seems we have not really needed this after .wakeignore landed. Reopen if I'm wrong.
