### ISSUE TITLE
Conventions for logging lines on error

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#489]
It would be nice to handle logging in a regulated way.
To set the motivation, I feel that a successful build should not print anything at all (perhaps a progress bar), but just return an exit code 0 on success.

When a job runs, all the stdout/stderr could be captured and not displayed,
but with an option to pipe it through to the terminal if running verbose.

If a failure happens, dump the stdout/stderr output to the terminal with any other information we have about the job that failed (the command, wake source location, visible files etc)

**Comment by mmjconolly** [comment]
Here's something inspired by https://github.com/sifive/api-scala-sifive/pull/49#discussion_r490476471 that I havent tried to compile

```
export def runJobQuiet plan =
  plan 
  | setPlanStdout logVerbose
  | setPlanStderr logVerbose
  | runJob
  match (job.getJobOutputs | findFailFn getPathResult)
  Pass a = Pass job
  Fail e =
    def _ = print "Job failed:\n STDOUT: {job.getJobStdout}\n STDERR: {job.getJobStderr}"
    Fail e
```

**Comment by terpstra** [comment]
I was going to implement this when I realized that the default values for stdout already ARE logVerbose. In other words, unless you specify '-v' you will not get standard output. Standard error is set to logWarn, which is probably correct also.

So I think all we really want to change is that we set Echo default from Normal to Verbose... and make all the source / hash jobs only echo on Debug.

**Comment by terpstra** [comment]
Dumping failed jobs is already supported via `wake --failed` after the build completes, so we have that too.

So I think the actionable item here is to modify the default for Echo and implement #488. Then we need to clean up the warnings in the source code that are spamming stderr. If a job really should silence stderr, because it is not printing warnings, that can still be done on a per-Job basis.
