### ISSUE TITLE
wake manifest, or an allow-list for *.wake source files to be compiled

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#494]
It would be nice to be able to have an allow list of wake source files, rather than using the current search method.

Additionally, if a workspace/repository had a file like `wake.manifest` then wake could use that to determine that it should put the wake.db in that directory and at the same time not search for *.wake files. 
This would also help with command line wake script invocations as we would then know where to make the wake.db

**Comment by terpstra** [comment]
I agree a new sentinel file to expect at the workspace root is a good idea. Right now it uses `wit-lock.json` for this. Perhaps `.WORKSPACE` or something similar?

Now that wit is being retired, we could switch wake over to a white-list instead of black-list source file policy, but I do not plan to do that immediately.

**Comment by terpstra** [comment]
Both of these ideas got implemented a while back:
- there is now '.wakeroot' for auto wake.db creation
- there is a .wakeignore to control source file discovery
