### ISSUE TITLE
flock() man page claims NFS is not supported, suggests fcntl instead

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#593]
I can't point to a specific issue that this has caused, but found it concerning to read:
`flock() does not lock files over NFS. Use fcntl(2) instead: that does work over NFS, given a sufficiently recent version of Linux and a server which supports locking.`
(from https://linux.die.net/man/2/flock)

We use `flock` in the fuse daemon to check if another daemon is running:
https://github.com/sifive/wake/blob/master/fuse/daemon.cpp#L1388

**Comment by terpstra** [comment]
This is fine.

flock on nfs just ensures locks work on the LOCAL machine. So if you lock a file on gamma03 and someone else locks the same file on gamm05, both locks succeed. However, you can't lock the file twice on gamma03.

Since running the daemon creates a local mount, this lock-only flock() behaviour is actually what we want.
