### ISSUE TITLE
Support catching the bad object in the else case of a require

### ISSUE THREAD

**Issue by colinschmidt** [sifive/wake#612]
I'd like to be able to append info to an error message that comes from a require.
Something like:
```
require Pass parsed =
    parseJSONFile sourceJSON
else
    Fail (makeError "Source JSON is bad: {innerFail.message}")
```
But currently I don't think I can get a handle on `innerFail` and so are forced to fallback to a match on the expression with another level of require after that.

**Comment by terpstra** [comment]
As discussed on slack, the accepted best practice is to combine `require` with `match`.

For example,
```
require Pass value = match (parseJSONFile sourceJSON)
   Pass x = x
   Fail f = Fail (makeError "Source JSON is bad: {getErrorMessage f}")
```

It's a bit over-kill in your example, since you are just working with another `Result`, but in the case where you have a lot of conditions to work out, it's the right pattern to have at the ready; eg:
```
require Pass xyz = match abc
   a, Nil = Pass a
   a, _   = Fail  "Too many inputs"
   Nil    = Fail "No input provided"
```
