### ISSUE TITLE
Value definition cycles crash the LSP but not the extension

### ISSUE THREAD

**Issue by ag-eitilt** [sifive/wake#721]
I have found another issue when using the VS Code extension, this time when Wake runs into a "value definition cycle".  Unlike #705 where the crash is very clearly signposted in the extension output, this failure case is more insidious: the "Output" tab shows a perfectly happy extension, no crash message pops up, and the Wake package is correctly added to the breadcrumbs, but the symbol hovers/breadcrumb and error detection (though interestingly not the unused variable warnings) stop working.

The following might be a slightly more-more-than-minimal example, but when I tried to write one from scratch, I couldn't trigger the error.

```
# This annotation is parsed successfully:
def exampleCycle (wrapped: List (Option a)): List a = match wrapped

# This one gives the following error when `wake` is run:
#     Value definition cycle detected including:
#         exampleCycle@argparse at src/parser.cpp:602:1
# def exampleCycle: List (Option a) => List a = match _

    Nil = Nil
    x, xs =
        def as = exampleCycle xs
        match x
            Some a = a, as
            None = as
```

**Comment by terpstra** [comment]
Thank you for the bug report.

So, the first version defines a function, which is legal to call itself recursively.
Due to an internal implementation detail, the second variant is treated like a value, which may not be cyclic.

If you run `wake` you'll see this:
```
src/dst/todst.cpp:822:1: definition of 'exampleCycle@build_wake' references 'exampleCycle@build_wake' forming an illegal cyclic value
>>> Aborting without execution <<<
```

The problem is the the source file locator! It says the bug is in todst.cpp... which might even be correct, come to think of it, since this probably should be treated as a function, not a value.

You can see in the problems tab of vscode that this error message is present, too, but VScode is super confused because it has no idea where to find todst.cpp to show you the error.

As for the type hover and go-to-definition, those don't work if wake can not figure out how to order your top-level definitions. Perhaps this algorithm could be made more robust, by erasing the cyclic definitions, and attempting to continue, but right now it just gives up.

Try this much more simple example:
```
def hax = hax + 1
```

This time you will get the error with a correct location, but go-to-definition/etc won't work until you fix the problem.

**Comment by terpstra** [comment]
Here's a smaller test-case:
```
def fn: a = \x fn x
```

**Comment by ag-eitilt** [comment]
I had a feeling it was a function/value issue, but forgot to update the report with that intuition.

Looks like the main issue I had got fixed since the 0.1.5 release; the problems tab didn't list anything, and the error location was given as `src/parser.cpp:602` rather than `src/dst/todst.cpp:822`.  I rebuilt the extension from the current master, and it reports properly now.  Thanks!

**Comment by terpstra** [comment]
This is definitely a bug.

**Comment by terpstra** [comment]
The simplest fix is to just report a correct location inside the offending wakefile, instead of pointing at the C++ internals. I'll definitely at least do that.

Ideally, I'd also like to fix this so that your example still count as a function, instead of a value, but this is hard, because the type signature is applied AFTER the function definition. There are a lot of places in the code that decide that something is a function only if the top-level expression is a lambda.

**Comment by ag-eitilt** [comment]
Ah, I can see those both being desirable; the first especially, though the second would be nice as well.

**Comment by terpstra** [comment]
The third improvement this brings up is to improve the definition reordering pass, to delete the cyclic part and "soldier on".
