### ISSUE TITLE
Skip job inputs specification entirely ?

### ISSUE THREAD

**Issue by ftucky** [sifive/wake#759]
Thank you for the wake project. I’ve been looking for something of the kind for 20 years: be able to plug any program in a build system and be absolutely confident that the result I get is the right one. [i.e., no infamous make clean; make]. Eventually, you guys are looking at this problem from the right perspective.

From wake’s README: 
**In wake, if you under-specify the inputs, the build fails every time. If you over-specify the inputs, wake automatically prunes the unused dependencies so the job will not be re-run unless it must.
You almost never need to tell wake what files a job builds; it knows.**

Indeed, thanks to fuse, wake knows. It knows all the files a job has used (or even attempted to) and all the files a job has produced. 
Since it knows, why does wake require user to capture job inputs _at all_ ?
Capturing the job inputs is boilerplate. Beyond usual compilers, many other programs, including commercial ones would be worth bolting into a build. Predicting which files those programs actually peek during their execution is hardly possible at all. Wake _verifies_ that capture, which is a tremendous enhancement compared to classic build systems, but would it be possible to get completely rid of it ?

On the other hand, telling _what a job builds_ is natural. Better: job production is the reason for executing it. 

Imagine user-captured rules describe a pathname-->job function. For any pathname, wake gets an executable job (typically a script), if any, expected to _create_ that pathname. Note there’s no reason for the function to be injective: multiple pathnames may be produced by the same job.
From that point, it seems possible to unroll a complete lazy evaluation recursion.
When user requests a pathname, wake identifies the job to build it, and as that job executes and accesses input files, those files are themselves rebuilt on the fly, exactly as in a functional programming evaluation. As such, any job may be memoized in a shared cache, for future reuse, by anyone.

I would highly appreciate your views about the pertinence, value, or feasibility of the approach.

**Comment by mwachs5** [comment]
Thanks for your interest in wake!

One of the main usages of wake is to ensure that each build step could be made relocatable. You specify your inputs so that if you want to run a given step "somewhere else", you know what things you need to transport "to" and "from" the other location. While this could be discovered as you go along by the running process, that is more complex to implement an "on demand" providing of the necessary inputs.The wake designers (my impression, I am not one of them) opted for a "sufficient, not necessary" approach to specifying the inputs.

Hope that makes sense, and hope someone will correct me if this understanding is wrong!

**Comment by terpstra** [comment]
I've been thinking a bit more about this idea. I want to rephrase the proposal slightly, which I think also makes the analysis easier.

You have a user-created table from output filenames to jobs. Those filenames can include 'glob' expressions, like build/myjob/*, but no two jobs in the table can create the same output (including due to glob overlap). When a job runs, only access to files in the table are allowed, access to other files results in file-not-found. Any file accesses cause the unique subordinate job to run. Any directory readdir() causes all jobs which output in that directory to run.

You run the build by asking for a file. That kicks off the lazy memoized evaluation of the necessary jobs.

There are two major theoretical downsides to this approach:
- memoization cannot benefit from 'happy accidents' (as previously discussed) -- you can only prune entire subtree evaluations
- lazy evaluation exposes no parallelism -- a job stops when it discovers a subordinate job must run

Compare this to wake:
- the wake language is explicitly eager => all subexpressions are known to run and so run in parallel
- you have a superset of the inputs provided before the job runs => solves both the two problems with the lazy approach

There are of course a bunch of other real-world / uninteresting problems with the lazy approach (blocking reads this long is likely to cause issues in the kernel, jobs start and stop a lot which is bad for memory utilization, ...)

**Comment by ftucky** [comment]
Hey ! Happy to see you fiddling with the idea !

> You have a user-created table from output filenames to jobs. Those filenames can include 'glob' expressions, like build/myjob/*, but no two jobs in the table can create the same output (including due to glob overlap). When a job runs, only access to files in the table are allowed, access to other files results in file-not-found. Any file accesses cause the unique subordinate job to run. Any directory readdir() causes all jobs which output in that directory to run.

Overall the description is correct, however
(1) On the top of wildcards, the glob expressions of the table may also contain significant arguments, like
build/{myjob}-{opt}/output-dir/{any}, with adequate regexp for {myjob} {opt} and {any}. This folds entries in the table doing "almost the same thing" into a single one. A primary objective is to maintain that "makefile" as short and generic as possible, in order to ease maintenance and changes-of-policy. As a consequence, the (virtual) _unfolded_ table you describe would be infinitely long. 
(2) The readdir() policy cannot be as simple as running all the jobs which output in that directory, precisely because that subset of the virtual, unfolded table may itself be infinite ! Imagine the hypothetical tool is used to construct FIRRTL files of an adder with {N} input ports. The firrtl files happen to end up in a single directory ( build/adders/5bits/{N}.firrtl ). A ls in that directory should cause all the possible 5bits adders to be generated !

> memoization cannot benefit from 'happy accidents' (as previously discussed) -- you can only prune entire subtree evaluations. 

No I disagree. 
You said: [I added files BBB and CCC for clarity]
> Here is the problem with that approach:
Rule A previously used file BBB form rule B and then file CCC of rule  C.
Rule B previously used file X
Rule C previously used file Y.
>
> File X and Y have both been changed.
>
> Rule A's pilot runs, calling pilot for B + C.
> B's pilot detects the change in X and re-executes.
> C's pilot detects the change in Y and re-executes.
> A's pilot detects the change and re-executes.

I think you are wrong on two points. 
* A's pilot seeks the changes in BBB and CCC, which may not have changed though B and C have been re-executed.
* When A's pilot runs, it has to call B pilot. It may then wait for B's pilot verdict, and directly go to A re-evaluation should BBB have changed. (Or proceed to C's pilot should BBB have _not_ changed). Proceeding to C's pilot ignoring BBB verdict is itself a speculation.

> lazy evaluation exposes no parallelism -- a job stops when it discovers a subordinate job must run.

Yes ! Somehow, parallelism _requires_ predicting what a job will need before it actually does.
Wake forces the user to recite a superset of job's inputs. Any false positive triggers unnecessary evaluations, which yourself qualified as _very dangerous_.
 
The hypothetical tool I have in mind proposes a slightly different approach of responsibilities.
* The "baseline" is exactly what you describe. "User" must write output_path-->job table, I believe it can be brief and generic. No "suspected inputs" recitation. Result is perfectly functional and reliable. Initial evaluation is completely linear, Re-evaluation (through pilot phases) subject to controlled speculation. 
* Note that a job may create parallelism by itself, by requesting different paths in different threads. That remark may be turned into an official speculation option, whose only impact is performance (parallelism) ; functionality and reliability are unaffected. I suspect "salting" that speculation in a few rules where prediction is easy is enough to yield sufficient parallelism.

**Comment by terpstra** [comment]
(I left out your generification of the table, as I think that's a mostly irrelevant front-end issue)

> The readdir() policy cannot be as simple as running all the jobs which output in that directory

The job that performs the readdir() might be outputting into that directory, too. Probably you would need policy to forbid stuff like that.

> > memoization cannot benefit from 'happy accidents' (as previously discussed) -- you can only prune entire subtree evaluations. 
> Proceeding to C's pilot ignoring BBB verdict is itself a speculation.

So your proposal is to just run the dependency re-evaluation in sequence, not in parallel? Then I agree (modulo the usual concerns that an otherwise deterministic program may not perform file accesses in the same order upon re-execution).

> > lazy evaluation exposes no parallelism -- a job stops when it discovers a subordinate job must run.
> 
> Yes ! Somehow, parallelism _requires_ predicting what a job will need before it actually does. Wake forces the user to recite a superset of job's inputs. Any false positive triggers unnecessary evaluations, which yourself qualified as _very dangerous_.

I agree that unnecessary things may run. However, I'd argue that because the superset of jobs are supplied by the user, it is less dangerous, because the user has explicitly told you to run those jobs first, even if it was unnecessary. The situations where I think you can run into real trouble are when you try to predict (without user input) what to run. You might run a job which actively interferes with the actually required alternative dependency.

I guess what we're saying is that lazy can work, but to get parallelism, you either need speculation (which means you need a recovery strategy to undo mistakes) or user input (which mostly absolves you of responsibility for any unnecessary/conflicting work).

> I suspect "salting" that speculation in a few rules where prediction is easy is enough to yield sufficient parallelism.

If you meant 'seeding', where you allow the user to specify in the rules a few known dependencies, I mostly agree. The user can keep adding extra 'pre-known' dependencies until their parallelism target is achieved.

This is a neat theoretical idea. I fear it probably won't work in practice, with existing tools, but cool nonetheless.
