### ISSUE TITLE
precise start and end times for jobs

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#794]
It could be nice to store (perhaps in the database) the precise start and end times for jobs.

This would allow us to used dumped output with a graphing program to look at the concurrent execution. Such a graph would be useful to see how time is spent.

I think the database already has the runtime for a job, but that the end time for the job is only accurate to 1 second

**Comment by terpstra** [comment]
Right. As you note the database currently has runtime (as reported by the runner) and endtime (in seconds, as recorded by wake). We could change this to starttime + endtime in nanoseconds (as recorded by wake). Note that `starttime + runtime != endtime`, because `runtime` is a statement about execution time, which may be much less than the scheduling window tracked by `starttime` and `endtime`.
