### ISSUE TITLE
Inline file edits triggering multiple-file-output errors

### ISSUE THREAD

**Issue by ag-eitilt** [sifive/wake#836]
In trying to write Wake targets for code linters, it's come up that trying to pass a file through multiple jobs which could edit it inline can easily trigger `File output by multiple Jobs` errors.  I'm wondering about the viability of disabling that check if the output file(s) it lists are all listed in every visible list involved -- basically saying that we don't want new files created by multiple jobs, but that we accept *existing* files changed by multiple jobs so long as their location in the file system remains the same.  There's probably going to be a lot of things confounding this (job ordering and the potential for race conditions through concurrent edits come to mind), but it is a feature people expect from Make, and might be one point of annoyance when switching to Wake.

**Comment by terpstra** [comment]
No.

**Comment by terpstra** [comment]
`make` does not work in this situation, either. It just makes your build non-deterministic.

The only way I can see to make this a safe feature would be to completely virtualize the workspace, so that you supply a filename and hashcode pair to the visible list. Then, we make whichever hash code you referenced available under that path. However, going that route will make things very confusing to people, since now you can have different file contents under the same path, depending on the job being run.

In the past, I've proposed:
- have the linter build rule produce a 'change-set' tarball or patch
- the user (or a script) can then accept/apply that change-set to the source files outside of the build

**Comment by ag-eitilt** [comment]
Yeah, I definitely agree we don't want to get into hashed file references.  And the non-determinism is something I was concerned about as well, but I didn't think about the Make side deeply enough to realize that it would obviously be an issue there too.  The only possible way I see for solving it, then, would be some mechanism for explicitly serializing a pair of jobs, and it seems like even trying to implement that would mean we lose way too much of the database benefits for something that is only rarely helpful.  At that point, we may as well just call out to a shell script.

**Comment by terpstra** [comment]
If you think about a developer's working loop, it goes something like: edit files, run build+tests, debug, edit files, run build+tests, debug, ...

What makes the linter-rewriter case strange is that the build changes the source files, which you generally *don't* want the build to ever do. I do agree that you probably want the build system to be in charge of determining which lint changes should be made to source files, but I'm not so sure that the build should be responsible for actually applying those changes.

On a personal level, I don't like tools changing my code without my permission. However, I know I'm in the minority at this company on this issue.

**Comment by ag-eitilt** [comment]
I'm with you in that minority.  Show me everywhere I need to fix, but let me fix it myself.  I basically just posted this because it *did* come up, and it seemed like a complaint which was worth logging.

**Comment by richardxia** [comment]
> At that point, we may as well just call out to a shell script.

It is extremely tedious to set up a parallel build process as a set of shell scripts, and I say this with first-hand experience. It makes it much more difficult to keep the two environments in sync, since you have the Wake way of installing packages vs. the bash script way of installing packages, the Wake way of invoking the linting tool vs. then the bash way of invoking the linting tool with additional flags that tell the tools to actually modify the source files, and then finally the Wake way of running multiple linting tools at once, reporting a summary of the results at the end vs. implementing the exact same thing with the bash scripts. The bash scripts easily fall out of date, especially if they're not being run as part of CI.

> If you think about a developer's working loop, it goes something like: edit files, run build+tests, debug, edit files, run build+tests, debug, ...

Sorry, I disagree. The _modern_ developer's working loop consists of: edit files, run code formatter, run lint, edit files, run build+tests. Code formatting and linting is now part of an even tighter loop than running tests.

> What makes the linter-rewriter case strange is that the build changes the source files, which you generally _don't_ want the build to ever do. I do agree that you probably want the build system to be in charge of determining which lint changes should be made to source files, but I'm not so sure that the build should be responsible for actually applying those changes.

I don't understand the exact boundary between what you are calling part of the "build" and outside the "build", but the "build" here is responsible for fetching external packages and installing them into the development environment, which is _separate_ from a production environment. If the build constructs my environment, and I can only invoke my linter from an environment where it is installed, then don't I need to run the linter from the "build"?

> On a personal level, I don't like tools changing my code without my permission. However, I know I'm in the minority at this company on this issue.

Who said anything about the tools changing your code without your permission? If you don't want the tool to change your code, then don't ask the tool to change your code. No one is forcing you to do so, but when you  However, I'd much rather have a tool remove unused import lines or fix the indentation of my file than for me to have to manually do that myself.

**Comment by ag-eitilt** [comment]
Closing because I don't see any actionable items remaining here.  There might be a discussion on the role of formatters, etc., that can be continued but those aren't directly related to the initial report.
