### ISSUE TITLE
nit: building from tarball results in 'fatal:' from git-describe

### ISSUE THREAD

**Issue by timsnyder-siv** [sifive/wake#922]
https://github.com/sifive/wake/blob/daa72abd3676e7e0a69bef18cbc15496b24a104d/vendor/git.wake#L23

When I try to build wake from one of the release tarballs, the standard build.wake tries to run `git describe` at the line referenced above.  This results in a `fatal:` message because I'm not in a git worktree.

I assume that it doesn't materially matter for the build. Otherwise, why provide tarball artefacts, right? However, it might be nice for the wake lib to `git rev-parse --is-inside-work-tree` (or something like that) to determine if it is in a git repo before trying to run other git commands and not having things fail (and get registered as failed in the `wake.db`).

Feel free to close this 'won't fix' if you disagree.  Like I said, I'm 99% sure this doesn't matter.

**Comment by V-FEXrt** [comment]
I just tried this locally and I couldn't reproduce which tracks my expectations. The tarball artifact is setup so that it doesn't call into `git`. Can you confirm you used the ` wake_0.X.0.tar.xz ` tarball and not the auto generation "Source code" tarball?

I'm going to go ahead and close but feel free to reopen
