### ISSUE TITLE
If you're in a fuse directory when the job ends it doesn't get deleted

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#98]
Workaround:
```
$ sudo diskutil unmount [dir]
```

**Comment by terpstra** [comment]
This seems impossible for wake to solve. Either the fuse runner (and by extension wake) would have to hang indefinitely, or the directory does not get unmounted (current behaviour). Both are awful. I marginally prefer the current behaviour since sending SIGKILL to the mount at least solves this sometimes on linux with lazy unmount semantics.

**Comment by terpstra** [comment]
Since the mount is now managed by a daemon, it can safely outlive the build.
